remote_theme: benc-uk/theme-msdark
title: Azure In A Day
hide_github: true
favicon: https://www.freeiconspng.com/uploads/cloud-icon-16.png
buttons:
  - text: Home
    href: /azureday/
  - text: Exercises
    href: /azureday/exercises
icon: fas fa-cloud    