remote_theme: benc-uk/theme-msdark
title: Azure In A Day
hide_github: true
favicon: http://files.softicons.com/download/web-icons/vector-stylish-weather-icons-by-bartosz-kaszubowski/png/256x256/cloud.png